DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todo_list;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  hormone_history TEXT DEFAULT NULL,

  Trust INTEGER DEFAULT 5,
  Confidence INTEGER DEFAULT 5,
  Reward INTEGER DEFAULT 5,
  Sleep INTEGER DEFAULT 5,
  Money_Credit INTEGER DEFAULT 5,
  Energy INTEGER DEFAULT 5,
  Stress INTEGER DEFAULT 5
);

CREATE TABLE todo_list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  periodic INT DEFAULT 0,
  deadline TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,

  Trust INTEGER DEFAULT 0,
  Confidence INTEGER DEFAULT 0,
  Reward INTEGER DEFAULT 0,
  Sleep INTEGER DEFAULT 0,
  Money_Credit INTEGER DEFAULT 0,
  Energy INTEGER DEFAULT 0,
  Stress INTEGER DEFAULT 0

);


CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);