DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todo_list;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  hormone_history TEXT DEFAULT NULL,

  Love INTEGER DEFAULT 5,
  Reward INTEGER DEFAULT 5,
  Sleep INTEGER DEFAULT 5,
  Money_Credit INTEGER DEFAULT 5,
  Energy INTEGER DEFAULT 5,
  Stress INTEGER DEFAULT 5
);

CREATE TABLE todo_list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  periodic INTEGER DEFAULT 0,
  body TEXT,
  snooze INTEGER DEFAULT 60,
    
  Love INTEGER DEFAULT 0,
  Reward INTEGER DEFAULT 0,
  Sleep INTEGER DEFAULT 0,
  Money_Credit INTEGER DEFAULT 0,
  Energy INTEGER DEFAULT 0,
  Stress INTEGER DEFAULT 0

);

CREATE TABLE user_task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  task_id INTEGER UNIQUE NOT NULL,
  deadline INTEGER DEFAULT 1440,
  created TIMESTAMP NOT NULL DEFAULT  (datetime('now','localtime')),
  FOREIGN KEY (task_id) REFERENCES todo_list (id)
  FOREIGN KEY (user_id) REFERENCES user (id)
  
)